# Generated by Django 3.0.7 on 2020-06-30 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subCategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
    ]
