# Generated by Django 3.0.7 on 2020-07-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200703_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='parent',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
